### PR TITLE
Enable logging of SQL statements

### PR DESCRIPTION
**Pull request by djmitche**
This solves #48, using @rahulrrixe's commit from #173.

Rahul, what do you think?

### CODE REVIEW

**Comment by djmitche** [comment]
@Callek in Rahul's absence, r?

**Comment by rahulrrixe** [comment]
@djmitche Is more changes required in this?

**Comment by djmitche** [comment]
I don't think so -- I was asking you if the result looked good.  Do you see anything else that isn't complete?

**Comment by Callek** [comment]
Looks ok to me, I didn't test though. :+1:

**Comment by rahulrrixe** [comment]
@djmitche It is woking fine on my local system. :+1:

**Pull request merged**
