### PR TITLE
Suggest and require absolute imports

### PR DESCRIPTION
**Pull request by Callek**
We use absolute imports just about everywhere.  They're easier to read, as you're not left searching through a list of directories for the relevant file.  We should include that in the patch requirements doc and (not sure how) enforce that in validate.sh.

### CODE REVIEW

**Comment by Callek** [comment]
I solved this by using isort, which allows me to easily add the import to every py file, in the proper way.

Along with doing this, we get better "import enforcement" (with some actual changes to go along with it) in a way that doesn't forcibly touch files when you run it.... It also allows us to output a diff on checking, and enforce the `from __future__ import absolute_import` here.

@djmitche r?  (the best way to review this is probably sha by sha, rather than as one big hunk)

**Comment by Callek** [comment]
Also fixes #276

**Comment by djmitche** [comment]
I like it!

**Comment by djmitche** [comment]
One thought: it might be nice if the comment included a way to fix the ordering when validate fails -- that will help contributors who get a red X from travis.

**Pull request merged**
