### PR TITLE
Bug 1204758: stream mapfiles rather than building them in memory

### PR DESCRIPTION
**Pull request by djmitche**
@hwine do you want to have a look?

### CODE REVIEW

**Comment by djmitche** [comment]
Note that the tests only verify that we're getting the right result -- I don't know of a way to convince the MySQL libraries to indicate when they are actually downloading the data, but I assume that they stream when possible.

**Comment by hwine** [comment]
> Note that the tests only verify that we're getting the right result -- I don't know of a way to convince the MySQL libraries to indicate when they are actually downloading the data, but I assume that they stream when possible.

A quick way to verify is to curl the full mapfile for gecko-dev. Currently, results do not start to get returned until about 15-20 seconds in.

**Comment by djmitche** [comment]
Let's do that once this lands.  I don't think the staging DB has a full mapfile, so we'll need to wait for prod.

**Comment by hwine** [comment]
r+ -- I'll let you merge as you deploy.

**Pull request merged**
