### PR TITLE
Add a robots.txt

### LINKED ISSUE #281: Add robots.txt file to web root
We currently do not have a robots.txt. While there should be nothing valuable accessible without credentials, no reason to have spiders chewing through the sites.

### PR DESCRIPTION
**Pull request by ciobancai**
This fixes #281

### CODE REVIEW

**Comment by djmitche** [comment]
It'd be great to give more descriptive titles to your pull requests, and then mention the issue number within the comment (for example, "this fixes #281").

**Comment by djmitche** [comment]
The code looks good, but as codecov has suggested, needs a test.  I know it's really simple, but a test will help make sure that Jinja can find the template, for example.

**Comment by ciobancai** [comment]
As djmitche  said:
> The code looks good, but as codecov has suggested, needs a test. I know it's really simple, but a test will help make sure that Jinja can find the template, for example.

Added the test to check if robots.txt file exists

**Comment by djmitche** [comment]
I edited the description and title appropriately, too

**Comment by djmitche** [comment]
Thanks!

**Pull request merged**
