### PR TITLE
Use real HTTP verbs in treestatus

### PR DESCRIPTION
**Pull request by Callek**
For example, `REVERT` is not a standard verb.

### CODE REVIEW

**Comment by Callek** [comment]
ready for review @djmitche

**Comment by Callek** [comment]
Note coveralls is failing "patch" because one of the lines that was caught in my "need to indent" was previously untested.

**Comment by djmitche** [comment]
Looks good so far, but needs fixes to the frontend code to use the new method/argument.

**Comment by Callek** [comment]
@djmitche this UI is untested, but aiui this is how it should be done.

**Comment by djmitche** [comment]
yup, works for me

**Pull request merged**
