### PR TITLE
Add mapper documentation from wiki and docstrings

### PR DESCRIPTION
**Pull request by djmitche**
@petemoore

### CODE REVIEW

**Comment by petemoore** [comment]
lgtm!

**Comment by petemoore** [comment]
r+

**Comment by djmitche** [comment]
careful with that "merge" button -- the RoR for this repo isn't GitHub, so vcs-sync un-merges

**Comment by petemoore** [comment]
lol, thanks Dustin for pointing that out. Whoops.

On that note: Should we make github the RoR for this (and all other git.m.o RoR) projects (or even just blow away the mirror on git.m.o)?

The PR workflow is really nice, seems a shame not to have it, and also to risk losing commits from force-pushes from vcs-sync. I think other teams have demonstrated that github can work well as RoR (b2g, fxos automation, …).

**Pull request merged**
