### PR TITLE
Fold all relengapi blueprints together

### PR DESCRIPTION
**Pull request by djmitche**
This incorporates the Git history of all of the component projects (mapper, slaveloan, clobberer, and tooltool), so the list of commits is huge.  After the merges, there's a bunch of work to remove the hacks required to support a multi-repo project.  And I made a bit of an editorial pass through the documentation while flattening it.

A few benefits here:
 * A single version simplifies deployment and testing
 * With only a single project, we can easily use Alembic to manage the relengapi DB
 * We can refactor things without landing patches to multiple repos
 * Release notes can include changes to all code
 * Name collisions in DB tables, etc. cause errors before deployment to staging
 * It's still nice and easy to develop -- no external dependencies are required for a development deployment to pass its tests
 * Documentation feels less disjointed

### CODE REVIEW

**Comment by djmitche** [comment]
@mrrrgn @petemoore @selenamarie -- r?

**Comment by mrrrgn** [comment]
Yes, the centralization will be nice. :+1:

**Comment by djmitche** [comment]
Oh, and the coveralls failure is expected -- slaveloan and mapper both have low coverage

**Comment by djmitche** [comment]
@Callek curious what your feedback is, too

**Comment by selenamarie** [comment]
:+1: although, I feel like I don't have enough time to do an indepth review.

**Comment by djmitche** [comment]
OK.  I'm happy to allow time.  It's a lot of new and changed files due to the merge, and a lot of commits due to the merge, but really the interesting changes are in [commit 314128e and its children](https://github.com/mozilla/build-relengapi/compare/314128e...4e3cd5a)

**Comment by djmitche** [comment]
Merged (after merging in the latest in each of the other repos)

**Pull request closed without merging**
