### PR TITLE
Add special case for connecting to S3

### PR DESCRIPTION
**Pull request by djmitche**
The typical boto.connect_s3 method doesn't take a 'region' argument like
most of the others, so we use boto.s3.connect_to_region instead.

### CODE REVIEW

**Comment by djmitche** [comment]
@mrrrgn how's this look to you?

**Comment by djmitche** [comment]
I'd like to release relengapi-1.1.1 with just this change, since without it relengapi-tooltool's tests fail.  But there's stuff on master that I don't want to release just yet as it requires schema and configuration changes.

**Comment by Callek** [comment]
:+1: Note: I support the "release ... with this" if we don't munge history here (e.g. don't revert stuff on master, and make sure this merges in with relnotes and such)

**Comment by djmitche** [comment]
I was planning to cherry-pick onto the relengapi-1.1.0 branch and make the
release, then merge that into master.

**Pull request merged**
