### PR TITLE
Get better coverage

### PR DESCRIPTION
**Pull request by djmitche**
I was bored..

And yes. the apidoc bit is probably cheating, but I barely understand how docutils works, let alone how to test it.  Besides, the code is exercised by building the docs, and anyway it's not production code.

### CODE REVIEW

**Comment by Callek** [comment]
Not a fan of the nocover littered here especially in the docutils thing.

Can we do --omit for the docutils piece if need be instead? (at least for now)

I'd *love* the other error conditions to be tested somehow too.

(I'm not blocking on my comments, just not a fan of the approach)

**Comment by djmitche** [comment]
Can you say why you're not a fan?

**Comment by Callek** [comment]
because it feels like this is all stuff we could/should test not just ignore. (I've seen errors that were baffling in that doc code alone over the time I've worked on slaveloan so far as one example)

**Comment by djmitche** [comment]
Nobody that I know understands it well enough to test it.  Docutils is *extremely* obtuse.  And a failure in the doc code (a) will cause validation to fail and (b) won't cause production issues.

The coverage on these just from building the docs is pretty good - there were, I think, 5 missed lines.

I'd use --omit, but there *is* some production code in the file -- the stuff that's not under "no cover" in this patch.

**Comment by djmitche** [comment]
I was thinking `setup` was production code, but it's not - it's only used to set up the sphinx extension during `relengapi build-docs`.  So I switched to omitting.  @Callek ?

**Comment by Callek** [comment]
:+1:

**Pull request merged**
