### PR TITLE
Bug 1249414: Handle error other than BadData in processing signature

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by djmitche** [comment]
It turns out this isn't an issue with itsdangerous 0.24, but it's worth keeping the `except` and the test around.

**Comment by garbas** [comment]
:+1: 

@djmitche does it makes sense to add test for that new exception?

**Comment by djmitche** [comment]
I tried to, but as the coverage shows, with the upgraded version of `itsdangerous`, that branch is not reached.  Still, I think it's a good thing to have in place.  I'll mark the `except` block as not being covered, and also change the comment.

**Comment by djmitche** [comment]
updated - have another look?

**Comment by djmitche** [comment]
The travis errors appear unrelated to this particular change.

**Comment by garbas** [comment]
:100:

**Pull request merged**
