### PR TITLE
Updated command for building docs in README.md file

### PR DESCRIPTION
**Pull request by murarisumit**
Updated readme for : https://github.com/mozilla/build-relengapi/issues/363

### CODE REVIEW

**Comment by djmitche** [comment]
Thanks -- this option was removed in d9aa7a9beb6f08d15faf5a3d83c3e6ee5d3374b4 but I didn't fix it in the README.

**Comment by djmitche** [comment]
@murarisumit I'm curious - what brings you to hack on relengapi?  Are you looking for other tasks?

**Comment by murarisumit** [comment]
I was looking for some OSS project to contribute and learn. I wanted to contribute to mozilla and I'm devops, so all three brings me on relangapi. 

Sure if there is some task I can help with, I would love too;  but I wasn't able to understand the project, what it does. I tried to build it on dev env, looked here and there, still I wasn't able to understand use of it.

**Comment by djmitche** [comment]
Send me an email (dustin@mozilla.com) and we can figure out how to get started.  RelengAPI is pretty specific to our needs (it is the code behind https://api.pub.build.mozilla.org), so not something that would be useful elsewhere -- if that's what you meant.

**Pull request merged**
