### PR TITLE
logger.bind bleeds to other modules/scopes

### PR DESCRIPTION
**Pull request by djmitche**
So in both badpenny code and archiver code we use logger.bind, that seems to leak the binding outside of the scope you intend, e.g.:

```
-------------------- >> begin captured logging << --------------------
relengapi.blueprints.slaveloan.bugzilla: WARNING: No bugzilla user specified. (Set BUGZILLA_USER in config to fix) (task_id='a321
e6a9-0e45-4655-bb55-707f3b9bd5b8' task_name='relengapi.blueprints.badpenny.execution._run_job' request_id='a5267d58-4e94-40ab-83f
a-eba015fa9f80' archiver_task_state='STARTED' archiver_task=u'foo' user='anonymous:')
relengapi.blueprints.slaveloan.bugzilla: WARNING: No bugzilla password specified. (Set BUGZILLA_PASS in config to fix) (task_id='
a321e6a9-0e45-4655-bb55-707f3b9bd5b8' task_name='relengapi.blueprints.badpenny.execution._run_job' request_id='a5267d58-4e94-40ab
-83fa-eba015fa9f80' archiver_task_state='STARTED' archiver_task=u'foo' user='anonymous:')
relengapi.lib.testing.context: INFO: request: POST /slaveloan/loans/ (task_id='a321e6a9-0e45-4655-bb55-707f3b9bd5b8' task_name='r
elengapi.blueprints.badpenny.execution._run_job' request_id='a5267d58-4e94-40ab-83fa-eba015fa9f80' archiver_task_state='STARTED'
archiver_task=u'foo' user='anonymous:')
relengapi.lib.testing.context: INFO: response: 400 BAD REQUEST - You can't request loans on behalf of others. (task_id='a321e6a9-
0e45-4655-bb55-707f3b9bd5b8' task_name='relengapi.blueprints.badpenny.execution._run_job' request_id='83c8eef7-d805-4cd2-8609-d84
446ea6afe' archiver_task_state='STARTED' archiver_task=u'foo' user='anonymous:')
--------------------- >> end captured logging << ---------------------
```

from just a slaveloan fail (intentional fail in this case)

@djmitche @lundjordan either of you feel confident tackling this?

### CODE REVIEW

**Comment by djmitche** [comment]
The answer was "write a plugin".

**Comment by Callek** [comment]
:+1:

**Comment by Callek** [comment]
hrm in my local testing I'm not so sure this is fixed.....

**Comment by djmitche** [comment]
OK.. do you have data?

**Comment by Callek** [comment]
On this very cset, with a forced fail..:
```
======================================================================
FAIL: relengapi.tests.test_db.test_ensure_empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/callek/mozilla/obj/relengapi/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/callek/mozilla/git/build-relengapi/relengapi/lib/testing/context.py", line 133, in __call__
    wrapped(*given_args, **kwargs)
  File "/home/callek/mozilla/git/build-relengapi/relengapi/tests/test_db.py", line 72, in test_ensure_empty
    eq_(1, 0)
AssertionError: 1 != 0
-------------------- >> begin captured logging << --------------------
relengapi.blueprints.slaveloan.bugzilla: WARNING: No bugzilla user specified. (Set BUGZILLA_USER in config to fix) (user='anonymous:' task_id='ae2a87dc-63bc-464d-867a-a91f2ca0aab7' request_id='91f86c96-1a9d-4e88-b965-371fdb990e9a' archiver_task_state='STARTED' task_name='relengapi.blueprints.badpenny.execution._run_job' archiver_task=u'foo')
relengapi.blueprints.slaveloan.bugzilla: WARNING: No bugzilla password specified. (Set BUGZILLA_PASS in config to fix) (user='anonymous:' task_id='ae2a87dc-63bc-464d-867a-a91f2ca0aab7' request_id='91f86c96-1a9d-4e88-b965-371fdb990e9a' archiver_task_state='STARTED' task_name='relengapi.blueprints.badpenny.execution._run_job' archiver_task=u'foo')
--------------------- >> end captured logging << ---------------------
```

**Comment by djmitche** [comment]
Hm, how did you force that?

**Comment by Callek** [comment]
added eq_(1, 0) to the cited test at the end of the test

**Comment by djmitche** [comment]
Can you check whether the after_test hook is running?

**Pull request merged**
